name: tests

on: [pull_request, push]

jobs:
  tests:

    strategy:
      fail-fast: false  # don't cancel other matrix jobs when one fails
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]


    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]

    - name: Run All Tests
      working-directory: ./tests
      run: pytest