name: tests

on: [pull_request, push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]

    - name: Test cmv
      working-directory: ./tests
      run: pytest test_cmv.py
    - name: Test field
      working-directory: ./tests
      run: pytest test_field.py
    - name: Test irradiance
      working-directory: ./tests
      run: pytest test_irradiance.py
    - name: Test signalproc
      working-directory: ./tests
      run: pytest test_signalproc.py
    - name: Test spatial
      working-directory: ./tests
      run: pytest test_spatial.py
    - name: Test stats
      working-directory: ./tests
      run: pytest test_stats.py