name: test

on:
  push:
    branches: [ "labeling" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Test stats
      working-directory: ./tests
      run: pytest test_stats.py
